---
version: 2.0

jobs:
  build:
    machine:
      image: circleci/classic:201708-01
      #  - image: crystallang/crystal:0.24.2
    steps:
      - run: whoami
      - run: sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
      - run: echo "deb https://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential crystal
      - checkout
      - run: sudo crystal spec
